/** Artwork from `public/icons/` — kebab-case copies of the source PNGs. */
export const BRAND_ICONS = {
  logo: "/icons/g3q-logo.png",
  quizAttempts: "/icons/quiz-attempts.png",
  certificates: "/icons/certificates.png",
  aboutAbhinyan: "/icons/about-abhinyan.png",
  helpline: "/icons/helpline.png",
  correct: "/icons/correct.png",
  incorrect: "/icons/incorrect.png",
  time: "/icons/time.png",
  drag: "/icons/drag.png",
  changeSequence: "/icons/change-sequence.png",
  doYouKnow: "/icons/do-you-know.png",
  resultCertificate: "/icons/result-certificate.png",
  resultTrophy: "/icons/result-trophy.png",
  profilePhoto: "/profile-photo.jpg",
  navPractice: "/icons/nav-practice.png",
  navG3qAi: "/icons/nav-g3q-ai.png",
  navHome: "/icons/nav-home.svg",
  navProfile: "/icons/nav-profile.svg",
  quizPlayBg: "/quiz/play-bg.png",
  leaderboard: "/icons/leaderboard.svg",
  playedQuizCount: "/icons/plays-count.png",
  queTypeMcq: "/icons/que-type-mcq.png",
  queTypeMatch: "/icons/que-type-match.png",
  queTypeSequence: "/icons/que-type-sequence.png",
  questionsCount: "/icons/questions-count.png",
  rankStars: "/icons/rank-stars.png",
  shareQuiz: "/icons/share-quiz.png",
  copyResponse: "/icons/copy-response.png",
  aiNewChat: "/icons/ai/New Chat Icon.png",
  aiHistory: "/icons/ai/AI History Icon.png",
  aiSend: "/icons/ai/Send Message Icon.png",
  aiCopyResponse: "/icons/ai/Copy Response Icon.png",
  aiLikeResponse: "/icons/ai/Like Response Icon.png",
  aiDislikeResponse: "/icons/ai/Dislike Response Icon.png",
};
